# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GPS_RangeBearing.ui'
#
# Created: Thu Oct 27 11:29:24 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(475, 655)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.rangelabel = QtGui.QLabel(self.centralwidget)
        self.rangelabel.setGeometry(QtCore.QRect(50, 50, 251, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.rangelabel.setFont(font)
        self.rangelabel.setObjectName(_fromUtf8("rangelabel"))
        self.soglabel = QtGui.QLabel(self.centralwidget)
        self.soglabel.setGeometry(QtCore.QRect(50, 380, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.soglabel.setFont(font)
        self.soglabel.setObjectName(_fromUtf8("soglabel"))
        self.coordinateslabel = QtGui.QLabel(self.centralwidget)
        self.coordinateslabel.setGeometry(QtCore.QRect(50, 460, 211, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.coordinateslabel.setFont(font)
        self.coordinateslabel.setObjectName(_fromUtf8("coordinateslabel"))
        self.rangebox = QtGui.QLineEdit(self.centralwidget)
        self.rangebox.setGeometry(QtCore.QRect(50, 120, 371, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(26)
        self.rangebox.setFont(font)
        self.rangebox.setObjectName(_fromUtf8("rangebox"))
        self.coordsbox = QtGui.QLineEdit(self.centralwidget)
        self.coordsbox.setGeometry(QtCore.QRect(50, 490, 371, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.coordsbox.setFont(font)
        self.coordsbox.setObjectName(_fromUtf8("coordsbox"))
        self.bearinglabel = QtGui.QLabel(self.centralwidget)
        self.bearinglabel.setGeometry(QtCore.QRect(50, 210, 311, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.bearinglabel.setFont(font)
        self.bearinglabel.setObjectName(_fromUtf8("bearinglabel"))
        self.stopbutton = QtGui.QPushButton(self.centralwidget)
        self.stopbutton.setGeometry(QtCore.QRect(340, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.stopbutton.setFont(font)
        self.stopbutton.setObjectName(_fromUtf8("stopbutton"))
        self.sogbox = QtGui.QLineEdit(self.centralwidget)
        self.sogbox.setGeometry(QtCore.QRect(50, 410, 371, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.sogbox.setFont(font)
        self.sogbox.setObjectName(_fromUtf8("sogbox"))
        self.bearingbox = QtGui.QLineEdit(self.centralwidget)
        self.bearingbox.setGeometry(QtCore.QRect(50, 280, 371, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(26)
        self.bearingbox.setFont(font)
        self.bearingbox.setObjectName(_fromUtf8("bearingbox"))
        self.startbutton = QtGui.QPushButton(self.centralwidget)
        self.startbutton.setGeometry(QtCore.QRect(50, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.startbutton.setFont(font)
        self.startbutton.setObjectName(_fromUtf8("startbutton"))
        self.statusbox = QtGui.QLineEdit(self.centralwidget)
        self.statusbox.setGeometry(QtCore.QRect(170, 550, 251, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.statusbox.setFont(font)
        self.statusbox.setObjectName(_fromUtf8("statusbox"))
        self.statuslabel = QtGui.QLabel(self.centralwidget)
        self.statuslabel.setGeometry(QtCore.QRect(50, 550, 191, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.statuslabel.setFont(font)
        self.statuslabel.setObjectName(_fromUtf8("statuslabel"))
        self.statuslabel_2 = QtGui.QLabel(self.centralwidget)
        self.statuslabel_2.setGeometry(QtCore.QRect(50, 590, 191, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.statuslabel_2.setFont(font)
        self.statuslabel_2.setObjectName(_fromUtf8("statuslabel_2"))
        self.dirbox = QtGui.QLineEdit(self.centralwidget)
        self.dirbox.setGeometry(QtCore.QRect(50, 610, 371, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.dirbox.setFont(font)
        self.dirbox.setObjectName(_fromUtf8("dirbox"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "FSVPAD Logger", None))
        self.rangelabel.setText(_translate("MainWindow", "Range (m):", None))
        self.soglabel.setText(_translate("MainWindow", "Drifter SOG (kn):", None))
        self.coordinateslabel.setText(_translate("MainWindow", "Drifter Coordinates:", None))
        self.bearinglabel.setText(_translate("MainWindow", "Abs. Bearing (deg):", None))
        self.stopbutton.setText(_translate("MainWindow", "Stop", None))
        self.startbutton.setText(_translate("MainWindow", "Start", None))
        self.statuslabel.setText(_translate("MainWindow", "GPS Status:", None))
        self.statuslabel_2.setText(_translate("MainWindow", "Data Directory:", None))

